/**
 * Generates public/sitemap.xml for the NARA website.
 * Run with:  node scripts/generate-sitemap.mjs
 * Update the PUBLIC_ROUTES list below when you add new public pages.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const BASE = 'https://nara-web-73384.web.app';
const today = new Date().toISOString().slice(0, 10);

// [path, priority, changefreq] — public pages only (no admin/auth/payment/personal)
const PUBLIC_ROUTES = [
  ['/', '1.0', 'daily'],
  ['/about-nara-our-story', '0.8', 'monthly'],
  ['/divisions', '0.8', 'monthly'],
  ['/audiences', '0.6', 'monthly'],
  ['/contact-us', '0.7', 'monthly'],
  ['/government-services-portal', '0.9', 'weekly'],
  ['/fish-advisory-system', '0.8', 'daily'],
  ['/marine-forecast', '0.8', 'daily'],
  ['/live-ocean-data', '0.8', 'daily'],
  ['/live-vessel-tracking', '0.7', 'daily'],
  ['/weather-dashboard', '0.7', 'daily'],
  ['/stormglass-maritime', '0.6', 'weekly'],
  ['/nasa-ocean-color', '0.6', 'weekly'],
  ['/marine-spatial-planning-viewer', '0.7', 'weekly'],
  ['/open-data-portal', '0.8', 'weekly'],
  ['/scientific-evidence-repository', '0.8', 'weekly'],
  ['/knowledge-discovery-center', '0.7', 'weekly'],
  ['/digital-product-library', '0.7', 'weekly'],
  ['/library', '0.8', 'weekly'],
  ['/lab-results', '0.7', 'weekly'],
  ['/research-vessel-booking', '0.7', 'monthly'],
  ['/research-collaboration-platform', '0.7', 'monthly'],
  ['/public-consultation-portal', '0.7', 'weekly'],
  ['/export-market-intelligence', '0.7', 'weekly'],
  ['/emergency-response-network', '0.7', 'weekly'],
  ['/marine-incident-portal', '0.7', 'weekly'],
  ['/regional-impact-network', '0.6', 'monthly'],
  ['/partnership-innovation-gateway', '0.6', 'monthly'],
  ['/project-pipeline-tracker', '0.6', 'weekly'],
  ['/integration-systems-platform', '0.5', 'monthly'],
  ['/learning-development-academy', '0.7', 'monthly'],
  ['/aqua-school-directory', '0.6', 'monthly'],
  ['/podcasts', '0.6', 'weekly'],
  ['/media-gallery', '0.6', 'weekly'],
  ['/media-press-kit', '0.6', 'monthly'],
  ['/nara-news-updates-center', '0.7', 'daily'],
  ['/news', '0.7', 'daily'],
  ['/annual-reports', '0.7', 'monthly'],
  ['/analytics', '0.5', 'weekly'],
  ['/nara-act', '0.6', 'yearly'],
  ['/nara-digital-marketplace', '0.6', 'weekly'],
  ['/vacancies', '0.7', 'weekly'],
  ['/procurement-recruitment-portal', '0.6', 'weekly'],
  ['/site-map', '0.4', 'monthly'],
  ['/accessibility-statement', '0.3', 'yearly'],
  ['/privacy-policy', '0.3', 'yearly'],
  ['/cookie-policy', '0.3', 'yearly'],
  ['/terms-of-use', '0.3', 'yearly'],
  ['/security-policy', '0.3', 'yearly'],
  ['/data-subject-rights', '0.3', 'yearly'],
  ['/rti', '0.4', 'yearly'],
  ['/rti-disclosure', '0.4', 'yearly'],
];

const urls = PUBLIC_ROUTES.map(([path, priority, changefreq]) => `  <url>
    <loc>${BASE}${path}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
  </url>`).join('\n');

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs — ${today} -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;

const out = join(dirname(fileURLToPath(import.meta.url)), '..', 'public', 'sitemap.xml');
writeFileSync(out, xml, 'utf8');
console.log(`Wrote ${PUBLIC_ROUTES.length} URLs to public/sitemap.xml (lastmod ${today})`);
